### ISSUE TITLE
Is PHP >= 8.0 really needed?

### ISSUE THREAD

**Issue by Yeicor** [LibreBooking/app#153]
The PHP >= 8.0 requirement was added on this commit of the develop branch: https://github.com/LibreBooking/app/commit/264d837fc6baac09b3b38e27263772234b4b087d

PHP 7.4 seems to still work just fine (I didn't test all features). Supporting PHP 7 may still be interesting because https://github.com/LibreBooking/app/issues/151 blocks reports on PHP8.

**Comment by effgarces** [comment]
You are absolutely right, that one slipped through. I will be changing that over the weekend to php 7.4 probably

**Comment by effgarces** [comment]
Reverted on commit 3e9cd19735c8ef2ff3464c20e2d22ccb0aae4a71
