### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by AdamWelchUK** [LibreBooking/app#168]
I've recently updated after running 2.7 for longer than I should have done. Now it seems my date format is not what it was before. Here we typically use dd/mm/yyyy but booked is displaying mm/dd/yyyy. The default.timezone setting is set to europe/london.

I've also had to update my php version, but the php.ini settings seem the same unless I'm missing something.

![image](https://user-images.githubusercontent.com/38890921/213889385-5ad13d65-14ec-4358-bcae-0ca0a016622f.png)

I'd appreciate it if someone could throw some ideas my way.

**Comment by AdamWelchUK** [comment]
Changing browser seems to have fixed my issue. Don't I feel silly.

**Comment by AdamWelchUK** [comment]
Sorry, actually this issue is not resolved. Does anyone have any idea why my date format is wrong despite location settings being correct? I've gone back to the previous PHP version and this doesn't resolve it either.

**Comment by YZone** [comment]
Hi,

Check your browser: Settings / Languages / Preferred languages
Move ‘English” to the top, not ‘English (United States)’
Now the format should be dd/mm/yyyy

YZone

**Comment by AdamWelchUK** [comment]
You've got it YZone. Not noticed it on any other sites but that has fixed it.  Not a Booking issue.

Thank you very much.
