### ISSUE TITLE
Custom Attribute "required" for Collect Specific Cases not working

### ISSUE THREAD

**Issue by larjona** [LibreBooking/app#172]
Thanks for working in LibreBooking. We have an instance with 2.8.5.5 version and we're experiencing the same issue reported here: https://forums.bookedscheduler.com/viewtopic.php?t=5441
Steps to reproduce:
Create a custom attribute for Reservations. Select it as Required, and select "Collect for Specific Cases", Resources, and mark only one resource. 
Try to make a reservation leaving blank the custom attribute (no matter if the type es checkbox, select, or text field with a regular expression forcing a certain pattern). 
Obtained result: You can save the reservation and the Attribute is left blank.
Expected result: I was expecting not being able to save the reservation until I fulfill the attribute requirement.
Thanks!

**Comment by YZone** [comment]
Hi,

We are running v2.8.5 and there is no problem in adding a custom attribute “required” with “Collect Specific Cases”.
**Are you sure you are testing this with a ‘normal user’ account?**
If you test this with an Application Administration account, you will be able to create a reservation without filling in the required attribute.

YZone

**Comment by larjona** [comment]
Thanks for the quick answer. Indeed that was the issue, we were using an admin account to test doing the reservations. We have tried with a normal user account and everything works as intended. Thank you very much and sorry for the noise!
