### ISSUE TITLE
Docker repository

### ISSUE THREAD

**Issue by colisee** [LibreBooking/app#174]
Hi @effgarces,

We've been in touch some time ago and I would love to contribute to the new Librebooking organization by transferring my repository colisee/docker-librebooking.

If you agree, could you kindly invite me as a member of the librebooking organization, so that I can pass my repository (which would be renamed librebooking/docker).

Aside from the above, when do you plan to release a new version, so that I can attempt to dockerize it as well?

Best regards.

**Comment by effgarces** [comment]
Hi @colisee 
Yes, I remember, in fact I have you to thank you for the structure that librebooking now has "Librebooking/app". Thanks for your help and contribution.

Yes, I will be adding you shortly.

As for a release, my personal goal is to release a new "stable-ish" version around easter, so on the first half of next month.

**Comment by colisee** [comment]
Hi @effgarces 
I just transferred my docker-librebooking repository to the librebooking organization in github.

Now, I can create a librebooking profile on the docker hub and generate the container image under librebooking/librebooking if you agree. Alternatively, or in addition, I can also check how to create the container image on the github docker repository. 

Could you please send me an email to colisee@hotmail.com so that I can later share with you the password on docker hub.
