### ISSUE TITLE
gregwar captcha not working ...

### ISSUE THREAD

**Issue by johnnyBrandom** [LibreBooking/app#177]
LibreBooking app appears fully operational except for the basic captcha feature (gregwar/captcha). When attempting to register a new user with the captcha feature enabled, there is no captcha on the registration webform - just the missing image icon ('''?'''):
![Screenshot 2023-03-18 at 1 28 10 PM](https://user-images.githubusercontent.com/42355639/226123180-3b519266-59c7-4ff8-9409-b756cb414c66.png)

 where the captcha should be. The form will not register the new user because it's not possible to verify the captcha. When configured to not use captcha, registration works as expected.

Traced the failure to line 50 of code in file lib/Application/CaptchaService.php:

`        $url = new Url(Configuration::Instance()->GetScriptUrl() . '/Services/Authentication/show-captcha.php');
`

The file '''show-captcha.php''' file is not present in this directory so an internal server error 500 (Failed to load resource) occurs at this line.

'''config.php''' has only the basic registration.captcha.enabled set to true - not the recaptcha as so:

`$conf['settings']['registration.captcha.enabled'] = 'true';`
...
<code>
$conf['settings']['recaptcha']['enabled'] = 'false';
$conf['settings']['recaptcha']['public.key'] = '';
$conf['settings']['recaptcha']['private.key'] = '';
</code>

Is it possible there are additional installation or configuration (other than as described in README's) steps needed for captcha? My development environment is a vagrant lamp stack with the following php modules installed:

`sudo apt-get install -y php7.4 php7.4-bcmath php7.4-bz2 php7.4-cli php7.4-curl php7.4-intl php7.4-json php7.4-mbstring php7.4-opcache php7.4-soap php7.4-xml php7.4-xsl php7.4-zip libapache2-mod-php7.4 php7.4-mysql php7.4-gd composer`

Running:
`Server version: Apache/2.4.29`
`Description:	Ubuntu 18.04.6 LTS`
`mysql  Ver 14.14 Distrib 5.7.41`

Thanks

**Comment by johnnyBrandom** [comment]
> ...
> 
> Traced the failure to line 50 of code in file lib/Application/CaptchaService.php:
> 
> ` $url = new Url(Configuration::Instance()->GetScriptUrl() . '/Services/Authentication/show-captcha.php');`
> 
> The file '''show-captcha.php''' file is not present in this directory so an internal server error 500 (Failed to load resource) occurs at this line.

Well - my mistake. It seems the file '''show-captcha.php''' is present but is responsible for causing the internal server error - probably by failing to generate the captcha image. Not sure why that's not happening? Will keep digging ...

**Comment by effgarces** [comment]
Hi, thanks for the report. I recently replaced both captchas with updated versions, recaptcha now is on version 3 and I moved from securimage to gregwar/captcha. 
The list of modules seems to be ok, gregwar/captcha requires php-gd and mb-string and also both sugestions, as seen on the log are not required and are only used in development to check for compatibility.

I checked librebooking on my vm with php7.4 to 8.1 and it all seems to work properly, so I'm wondering what could be causing this. Does the error.log from apache2 contain anything that might shed a light?

**Comment by johnnyBrandom** [comment]
The virtual hosts configuration turned out to be a red herring (although I still don't know why removing the vhosts file allowed things to work) ...

The error preventing the gregwar captcha from loading is resolved by enabling apache2's **headers** module. You must restart the server after for the change to take effect. The installation docs should probably include this information as part of the apache2 configuration (along with enabling the **rewrite** module) since these two are not typically enabled by default and I've found they both are needed by LibreBooking. The **rewrite** module is used to manipulate url's; the **headers** module is user to control and modify http request and response headers. I have revised the LibreBooking installation docs in my fork to advise enabling these modules and will issue a pull for that change that you may choose to accept or reject as you deem fit. Thanks.
