### ISSUE TITLE
LDAP Authentication Error "...config file is not writable..."

### ISSUE THREAD

**Issue by JensWendt** [LibreBooking/app#185]
We run Booked Scheduler 2.8.5.4

I try to configure SSL encryption for our LDAP connection following the How-To from your Wiki.
But under `Application Configuration` when I select `Authentication-LDAP` from the dropdown-menu it gives me an error 
`The config file is not writable. Please check the permissions of this file and try again.`
in a red box underneath the the dropdown-menu and
`Warning: chmod(): Operation not permitted in /var/www/html/booked/lib/Config/Configurator.php on line 143`
a bit more info above the dropdown-menu.

I checked the line in question and indeed it tries to `chmod` some some `$configFile`.
I tried for 4 or so different config files I could think of to set permissions to 777 as root, but had no success.
Can someone elucidate which config file is meant here?

I am pretty sure we have a standard installation and did not fiddle too much with any config files. I have to admit though, that this happened before my time, therefore I cannot guarantee it.

**Comment by arnogramatke** [comment]
IIRC the LDAP plugin looks for the file `/plugins/Authentication/Ldap/Ldap.config.php`. This needs to be writeable by the webserver process. When you are on Debian, the Aapache process runs as user www-data, which is also member of the www-data group. So you could `chown root:www-data Ldap.config.php` and `chmod 775 Ldap.config.php`. Then you should be able to edit this config file from the web interface.

**Comment by JensWendt** [comment]
That was it! 
Thank you so much.
