### ISSUE TITLE
LDAP bind with "variable" binddn & bindpw

### ISSUE THREAD

**Issue by jonsito** [LibreBooking/app#196]
Hi All.
I'm trying to authenticate against an LDAP server where unauthenticated nor anonymous bind is not allowed, and the only way to retrieve ldap data is by providing user's name and password as follows:

/usr/bin/ldapsearch 
 -H ldaps://ldap.unit.org:636 
 -b ou=users,dc=unit,dc=org 
 -D uid=user.name@unit.org,ou=users,dc=unit,dc=org 
 -x -v -LLL '(uid=user.name@unit.org)' 
 -w user.passwd

That is: each user must provide their own username and password to get access. We have neither "readonly" nor "admin" access, just ask if username/password dupla is valid and retrieve associated data 

AFAIK Librebooking does not support "dynamic" binddn & bindpw. 
So I'm trying to patch code to insert "on the fly" these parameters.
Any hint? Is this "feature" planned in any future version?

Thanks in advance
Juan Antonio

**Comment by effgarces** [comment]
Unfortunately I have almost zero experience with LDAP and I'm unable to provide much help on this. At the moment the plan is to maintain the app, fixing bugs and add simple/easy to implement new features, I don't have anything planned on the LDAP front.

**Comment by jonsito** [comment]
OK. I have a patch that "works for me" (tm)
I use an extra ldap config option "provide.user.as.binddn" that, when true, if binddn/bindpw are null, tryies to bind using dn: uid={$username},{$basedn}
Here comes my patch. perhaps you could consider including into source.

[provide_user_as_binddn.patch.gz](https://github.com/LibreBooking/app/files/11712801/provide_user_as_binddn.patch.gz)

**Comment by colisee** [comment]
@jonsito ,

could you please tell us if you could solve your issue by changing the above file?
If yes, could you then close this issue?

Thanks.

**Comment by jonsito** [comment]
Hi.
Eventually I made a similar solution: our LDAP authentication server have some specific issues; but code seems ok to me.

Closing issue. Thanks.
