### ISSUE TITLE
Wrong Timezone

### ISSUE THREAD

**Issue by donaldrail** [LibreBooking/app#210]
Hello,

I have tried many different configurations, but I always get a different timezone than what I should. It always take me to a earlier timezone meaning the schedule shows an hour earlier than it should, so if I want to see the schedule as 8am to 4pm, it will display 7am to 3pm.

Using WAMP Server, on a windows machine. All newest version of software and OS.

Even if I change the config.php file : $conf['settings']['default.timezone'] = 'America/Halifax';, or I leave it as $conf['settings']['default.timezone'] = 'Etc/UTC';. I can change it at the "Schedules" level and put in the timezone there. It always displays the schedule an hour earlier than it should. In PHP, it shows correctly the timezone/time. 

What am I missing?

**Comment by YZone** [comment]
Hi,

The time zone can be set in three different places, check them all:
1.	Default time zone in ‘config.php’
2.	My Account / Profile / 'timezone'
3.	Application Management / Schedules / edit ‘layout (all times ...)’, check timezone

YZone

**Comment by donaldrail** [comment]
Thank you so much for answering YZone,

I had 2 out of 3. Never thought that changing option 2 : My Account / Profile / 'timezone' would make a difference. But it did! I understand now that this is at the user level.

It was by default at New York for my admin account.

My problem now: what do I do for all the users that will log in to the system with the New York timezone by default? How can I change this to the correct timezone ( America/Halifax ) ?

Thanks in advance,
Donald

**Comment by YZone** [comment]
Hi,
Once you have set the default time zone in the config.php file, when creating new users they will be using the correct time zone.
For existing users, change the user time zone one by one: Application Management / Users / ‘edit’.
If you have a lot of users, you can export the users list and use Excel to change the time zone column. Then import the list. Be sure to use the correct sequence of header. Use the ‘get template’ button to achieve this. USE IT WITH GREAT CARE in order not to corrupt the database! Try one user first.
YZone

**Comment by donaldrail** [comment]
Hello YZone,

Thank you so much for your help!!! I have been trying to figure out this problem for months...

This is a new instance of our Booked server so if I can correct this, we will be able to do the update to 2.8.6.

Thanks again,
Donald

**Comment by donaldrail** [comment]
Closing this issue.
Thanks again YZone!
