### ISSUE TITLE
Is there a reason why the api settings are not visibile on the web ui?

### ISSUE THREAD

**Issue by colisee** [LibreBooking/app#214]
Hi @effgarces,

Is there a reason for skipping the following 2 configuration settings in `config/config.php`?
```
$conf['settings']['api']['enabled'] = 'true';
$conf['settings']['api']['allow.self.registration'] = 'false';
```

Excerpt from Presenters/Admin/ManageConfigurationPresenter.php

![Capture d'écran 2023-08-05 120126](https://github.com/LibreBooking/app/assets/64310405/270899cc-0161-4f7f-a94c-cfea6e2f47d7)

Cheers.

**Comment by effgarces** [comment]
As far as I'm aware I don't see a reason for it.

**Comment by colisee** [comment]
Hi @effgarces,

In that case, I will issue a PR to enable the setup of the API section from the web ui.

Cheers.
