### ISSUE TITLE
Upgrading from 2.8.3 to 2.8.6 causes reservations not to load

### ISSUE THREAD

**Issue by FlaminWrap** [LibreBooking/app#218]
Hello,

I am trying to migrate an instance from 2.8.3 to 2.8.6. Everything works perfectly on 2.8.3 but after upgrading to 2.8.6 the bookings and calendar views stop working. The booking view hangs on Loading reservations and the Calendar view do not display anything but an empty calendar and some php errors. 

![1](https://github.com/LibreBooking/app/assets/97764630/d985bca5-8c2f-4537-817a-0b120e4c18af)

![image](https://github.com/LibreBooking/app/assets/97764630/f5a21251-fe8c-4db1-9fef-957fa780d3f1)

Any help would be appreciated.

**Comment by FlaminWrap** [comment]
So I have found the error message which is:

`<br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>18</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>19</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>20</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>18</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>19</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>20</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>18</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>19</b><br/><br/><b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/html/html/lib/Common/ContrastingColor.php</b> on line <b>20</b><br/>[`

**Comment by FlaminWrap** [comment]
Looks like `"BackgroundColor": "#orange",` is the problem as `#orange` is not a hex value.

`    {
        "StartDate": "1692788400",
        "EndDate": "1700092800",
        "Id": "1",
        "ReferenceNumber": "64e4889e19e3a615165841",
        "ResourceId": "1",
        "RequiresCheckin": false,
        "BorderColor": "",
        "BackgroundColor": "#orange",
        "TextColor": "#FFFFFF",
        "IsReservation": true,
        "IsBuffer": false,
        "IsBuffered": false,
        "Label": "Test",
        "IsPending": false,
        "IsNew": false,
        "IsUpdated": false,
        "IsOwner": false,
        "IsPast": false,
        "StartTime": "12:00 PM",
        "EndTime": "12:00 AM",
        "IsParticipant": false,
        "IsAdmin": true,
        "BufferedStartDate": null,
        "BufferedEndDate": null,
        "BufferedStartTime": null,
        "BufferedEndTime": null
    },`

**Comment by FlaminWrap** [comment]
Closing this as it is no longer an issue, for an unknown reason.

**Comment by 2Fac3** [comment]
After updating to 2.8.6.2 The booking view hangs on Loading reservations and the Calendar view do not display anything but an empty calendar but no php errors. 

![Image](https://github.com/user-attachments/assets/5253b40a-0d08-47a9-8b06-c3bbe37af64b)
