### ISSUE TITLE
PHP message: PHP Fatal error:  Uncaught Error: Class "Smarty"

### ISSUE THREAD

**Issue by VitorTakami** [LibreBooking/app#219]
I'm stucked in this error: PHP message: PHP Fatal error:  Uncaught Error: Class "Smarty" not found in /var/www/nginx/agendamentosic/lib/Email/SmartyEmail
My librebooking is 2.8.6 and php8-8.1.23
Could you guys help me ? Thanks

**Comment by colisee** [comment]
Hi @VitorTakami 

Could you please close this issue, since you opened the similar issue #234 ?

Thanks.

**Comment by VitorTakami** [comment]
Issue closed.
For the resolution check : https://github.com/LibreBooking/app/issues/234
