### ISSUE TITLE
Class Smarty not found

### ISSUE THREAD

**Issue by VitorTakami** [LibreBooking/app#234]
librebooking-2.8.6 and php8-8.0.30
The php file that show me the error is: lib/Email/SmartyEmail.php

**Comment by colisee** [comment]
Hi @VitorTakami ,

Did you use `composer` to install the required php dependencies, among which smarty ?
I noticed that this is not mentioned in the installation procedure...

**Comment by VitorTakami** [comment]
Hello @colisee .
I tried to run composer, bu it give me the error that requires php 8.1.0 and i'm running php 8.0.30.

**Comment by colisee** [comment]
It seems that the current version of librebooking (2.8.6) is developed with a minimum php version in mind: `8.1.0`. So, ideally, you should upgrade your environment to php 8.1.0 or greater.

If you cannot or do not wish to upgrade php on your system, then you can try to change the `composer.json` file and change the line `"php": ">=8.1",` to `"php": ">=8.0",`. But you are on your own from now on.

**Comment by VitorTakami** [comment]
OK, thanks @colisee .
I will wait some time to update my php on the system.
