### ISSUE TITLE
2.8.6.1 php error

### ISSUE THREAD

**Issue by michael-harman** [LibreBooking/app#237]
Getting this error when trying to do an upgrade from 2.8.6:

Was working before...php 8.1, mysql 5.7 (also tried 8), apache2

[Tue Sep 26 18:42:45.297572 2023] [php:warn] [pid 11801] [client 10.201.22.120:42210] PHP Warning:  Undefined array key "librebooking" in /var/www/html/lib/Config/Configuration.php on line 128
[Tue Sep 26 18:42:45.297620 2023] [php:error] [pid 11801] [client 10.201.22.120:42210] PHP Fatal error:  Uncaught Error: Call to a member function GetSectionKey() on null in /var/www/html/lib/Config/Configuration.php:133\nStack trace:\n#0 /var/www/html/lib/Common/Logging/Log.php(94): Configuration->GetSectionKey()\n#1 /var/www/html/lib/Common/Logging/ExceptionHandler.php(19): Log::Error()\n#2 [internal function]: ExceptionHandler::Handle()\n#3 {main}\n  thrown in /var/www/html/lib/Config/Configuration.php on line 133

**Comment by abaldoni** [comment]
@michael-harman Hello Michael, I have the same error.
How did you solve it?

Kindest regards,
A.
