### ISSUE TITLE
[Fri Sep 29 15:11:13.390516 2023] [php:warn] [pid 869] [client xxxxxxx] PHP Warning:  Undefined array key "REMOTE_USER" in /var/www/html/librebooking/plugins/Au> [Fri Sep 29 15:11:13.390757 2023] [php:warn] [pid 869] [client xxxxxx] PHP Warning:  Undefined array key "REMOTE_USER" in /var/www/html/librebooking/plugins/Au>

### ISSUE THREAD

**Issue by Nortag82** [LibreBooking/app#240]
Hello, having some login issues. AD has been working fine. but went live today witht his, and some users are not able to log in. 

apache log shows this. 

[Fri Sep 29 15:11:13.390516 2023] [php:warn] [pid 869] [client xxxx] PHP Warning:  Undefined array key "REMOTE_USER" in /var/www/html/librebooking/plugins/Au>
[Fri Sep 29 15:11:13.390757 2023] [php:warn] [pid 869] [client xxxxxx] PHP Warning:  Undefined array key "REMOTE_USER" in /var/www/html/librebooking/plugins/Au>

Any ideas?

**Comment by Nortag82** [comment]
It works fine on my PC. done a test. and had a pc i used initailly. Cleared the browser and now getting the same issue. can log in. but suuuper slow. and websites is almost non responsive

**Comment by sarkhanabbasov** [comment]
Hi, how did u resolve that?
