### ISSUE TITLE
Redirected to schedule.php when create/delete bookings

### ISSUE THREAD

**Issue by StuxNetV8** [LibreBooking/app#243]
Hey everyone,

When I create or delete a booking I will be redirected to "schedule.php" only and not the complete web address (http://booking-host.domain/librebooking/Web/....). However, the booking will be still created/deleted. Does someone have the ssame issue or has an idea on what is wrong there?

Librebooking 8.5.5
PHP: 7.4

P.S: During booking is also ignores the setting of the maximum amount of time this resource can be booked (e.g. 1day). Not sure if is due to the same error.

StuxNet

**Comment by treborin** [comment]
@StuxNetV8 , pls try to update to latest version [2.8.6.1](https://github.com/LibreBooking/app/releases/tag/2.8.6.1)

**Comment by StuxNetV8** [comment]
> @StuxNetV8 , pls try to update to latest version [2.8.6.1](https://github.com/LibreBooking/app/releases/tag/2.8.6.1)

Hey treborin, I can see that the LDAP issue has been solved. Great! Will try to upgrade soon!

**Comment by Pacifist8061** [comment]
Hello, 
I'm wondering if this issue is similar/the same as mine: When booking an event 2 weeks ahead, once the booking is created it redirects me to the current week's booking page instead of the week i was on (2 weeks ahead). It's very annoying when trying to create one's schedule in advance, I have to continuously go back to the week I'm doing. 
Not a programmer.

**Comment by StuxNetV8** [comment]
Finally having some time to recheck this issue I could find the (simple) reason for it!
script.url (was in my case) set to:
`hostname/Web`
instead of:
`http(s)://hostname/Web`
I'm not sure why I did this... I remember reading somewhere that not including this it will automatically work for non-ssl and ssl. I was being wrong there!

For anyone else having similar issues:
Enter http or https, your host name with full domain (FQDN) and every Subfolder until and incl. /Web because that might differ from every installation.

Thank you!
StuxNetV8
