### ISSUE TITLE
Issue with logging in upgraded software

### ISSUE THREAD

**Issue by socusa** [LibreBooking/app#244]
I have recently ugraded from 2.7.7 to 2.8.6.1 and when trying to load a page (register.php for example), I'm getting an error because it's trying to record output to /app.log. I modified log4php.config.xml in /config to include the actual log file name, but this had no effect. Can you tell me where I set the output log file? Thanks.

**Comment by effgarces** [comment]
log4php was replaced by monolog earlier this year, you need to set the path to the app.log file on the config.php file, or in the librebooking settings

**Comment by socusa** [comment]
Thanks

-

Keith Lynn
School of Computing
SHEC 1202
(251) 460-7643
