### ISSUE TITLE
Missing log4php.config.dist.xml is not present in LibreBooking/config

### ISSUE THREAD

**Issue by kordan** [LibreBooking/app#260]
In https://github.com/LibreBooking/app/blob/develop/doc/INSTALLATION.md
I read:
Logging is configured in /config/log4php.config.xml 
but the file log4php.config.dist.xml
is not present in [config](https://github.com/LibreBooking/app/tree/develop/config

**Comment by colisee** [comment]
Hi @kordan 

I believe that the file `INSTALLATION.Md` was not properly updated with the upgrade to version 2.8.6, for log4php has been replaced by Monolog. 

Now, you configure the logging parameters from the application settings menu. Please note that the file must exist before you change the application setup. 

If this answers your comment, then please close this issue.

**Comment by kordan** [comment]
Ciao Colisee and thanks for your answer.
I am not sure I understand what you mean with: "application settings menu". Do I need to look for settings in config.php or a "Setting" menu is available from the librebooking application running?
In both cases, I do not understand where I am supposed to operate.

Last: as you wrote the installtion.md should be updated. Maybe this issue is a "pro memory" of the need to update the file.

**Comment by colisee** [comment]
When you login as the administrator, there is an `Application Configuration` menu inside the librebooking web page, as you can see below:

![Capture d'écran 2023-11-10 170456](https://github.com/LibreBooking/app/assets/64310405/69496d3e-a154-4996-8151-3df4105c9290)

When you click on `Application Configuration`, you get the configuration page. Scroll to the bottom where you will see the `Logging` section.

![Capture d'écran 2023-11-10 171115](https://github.com/LibreBooking/app/assets/64310405/13eb5541-4b12-4499-aade-0cdff39fcf06)

**At the moment, I believe** that the log files `app.log` and `sql.log` must exist inside the specified log library, for the application does not create them. The level field can be either empty, `error` or `debug`.

I hope this will help you.

**Comment by kordan** [comment]
Super!
Thank you.

**Comment by colisee** [comment]
@kordan 

My pleasure. Could you please close this issue?
