### ISSUE TITLE
Slow creating and updating bookings

### ISSUE THREAD

**Issue by TwinMist** [LibreBooking/app#313]
Just moved over to 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
10.6.16-MariaDB-0ubuntu0.22.04.1
It is taking over a minute to save or update a booking
Any ideas?

thanks

**Comment by TwinMist** [comment]
Sorry was down to SMTP failing

**Comment by fuser77** [comment]
Hello, I have the same problem, could you tell us how you solved it?
