### ISSUE TITLE
Error after update latest Libre

### ISSUE THREAD

**Issue by KZalu** [LibreBooking/app#321]
Hello
We have been using phpschedulit/booked for years for our court reservations at the tennis club. No court rental only for our club members instead of a magnetic board. Now I had to update because our provider no longer supports PHP 7.4. So far it worked fine. Unfortunately I get a very long error message after login. After some clicks and refreshes the schedule appears. Can someone helps me? Or can someone support me - for a fee? I am not a programmer. Thank you very much! Here is the beginning of the error:
UnexpectedValueException: _The stream or file "/app.log" could not be opened in append mode: fopen(/app.log) [[function.fopen.php](https://secure.php.net/manual/en/function.fopen.php)]: Failed to open stream: Permission denied The exception occurred while attempting to log: [User= ()] Trying to log in as: zalka [File=/home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/lib/Application/Authentication/Authentication.php,Line=82] in /home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146 Stack trace: #0 /home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write(Array) #1 /home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/vendor/monolog/monolog/src/Monolog/Logger.php(611): Monolog\Logger->addRecord(200, '[User= ()] Try...', Array) #3 /home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/lib/Common/Logging/Log.php(82): Monolog\Logger->info('[User= ()] Try...') #4 /home/tennisc8/www/onlinereservation.tc-_

**Comment by marbuka** [comment]
Hi,
Since version 2.8.6 there are new log file locations for librebooking. They are mentioned in the new config.php file.
You need to create a directory `/var/log/librebooking` Inside make two placeholder files -`app.log` and `sql.log`

After that, change the owner of the directory and files to `www-data` and apply read/write permissions.

**Comment by KZalu** [comment]
Great! I will implement it straight away.
Thank you very much.

**Comment by KZalu** [comment]
Hi, 
One more question: where should this directory be located? I have the following path: home/tennisc8/www/onlinereservation.tc-uster.ch/TCUPlatz81/ - the structure of Librebooking.

**Comment by KZalu** [comment]
OK! Now it works fine! There was a "/" to much in the config.php.
Thanks,

**Comment by marbuka** [comment]
By default it's meant to be located in `/var/log` - common folder for logs of services running on a machine.
If it's not possible, you can specify other folder in your config file.
