### ISSUE TITLE
remove legend bar from schedule

### ISSUE THREAD

**Issue by craigb244** [LibreBooking/app#325]
Hellow

Anyone help removing or editing the legend?

I have use.per.user.colors set to true, this makes each booking the colour set to each user.

the issue i have is the legend strip causes confusion so ideally looking for a way to remove it entierly 

Thanks in advance for any help!

Craig

**Comment by treborin** [comment]
**File**: tpl/Schedule/schedule.tpl
Just delete lines with the block, starting from `{block name="legend"}` and end with `{/block}`, or comment these lines inside `{*` and `*}` as you can see on line 1.
Should be lines 225 to 240 in the original file.
After this, If you do not see any change on the screen, pls clear /tpl_c folder.


![image](https://github.com/LibreBooking/app/assets/31905622/87346023-407e-40b7-a9e3-abc00b748567)
