### ISSUE TITLE
Tags from 2.7.6 through 2.8.5 seem incorrect

### ISSUE THREAD

**Issue by JohnVillalovos** [LibreBooking/app#372]
@effgarces  I notice all of these tags currently point at commit: b8db051a2b85b325f2350547cde719d77c6e6e8f

I have put my best guess on what the commit should be for each tag, based on changes to `lib/Config/Configuration.php`

  * 2.8.5  -> 74f33655093701946f774353eeaf0760f7c1f852
  * 2.8.4 -> a7fadfaa519f54a6fd7d24bfb102c39397761639
  * 2.8.3 -> 2baebb5fe6508654d5f99f4b662025c54b0e9f0a
  * 2.8.2 -> 4f7db6b841c5c2ee4d8d1b5d14fd65a3fbf63519
  * 2.8.1 -> 3a8629d804a4109d0b7fcbfc2dbea228363927a1
  * 2.7.8 -> e9b5367b591e0a13057d0538bb0fde99ee989170
  * 2.7.7 -> 88d4673161a9e4c43a95d5796ea24a52dd70df96
  * 2.7.6 -> 0675f1d3081ffa20b9c96efdc989d920c3d0ff66

```
commit b8db051a2b85b325f2350547cde719d77c6e6e8f (tag: refs/tags/2.8.5, tag: refs/tags/2.8.4, tag: refs/tags/2.8.3, tag: refs/tags/2.8.2, tag: refs/tags/2.8.1, tag: refs/tags/2.7.8, tag: refs/tags/2.7.7, tag: refs/tags/2.7.6)
Author: Emanuel Garcês <effgarces@gmail.com>
Date:   Thu Oct 29 18:23:58 2020 +0000

    Update Readme.md with more information
```

**Comment by JohnVillalovos** [comment]
@effgarces Any thoughts on this? Thank you.

**Comment by effgarces** [comment]
Sorry, as per usual way too many things on my plate requiring attention. I took a quick look and the tags/commits seem to correspond. I will see about correcting this as soon as I can.

**Comment by JohnVillalovos** [comment]
Thanks!

**Comment by effgarces** [comment]
Forgot to return here to let you know that I already applied the tags to repo, hopefully without any major mistakes

**Comment by JohnVillalovos** [comment]
Thanks @effgarces !
