### ISSUE TITLE
first.day.of.week Spanish Calendar NOT working

### ISSUE THREAD

**Issue by ieovigo** [LibreBooking/app#385]
Hello,

In Spain, weeks start on Monday and we want Monday to be shown as the first day of the week on the calendar.

We have modified the default calendar so that the first day of the week is Monday, Sunday is still displayed.

The application (ver 2.8.6.1) does not have the option to configure it either via the web or in /config/config.php

On the Internet I have found that adding this parameter to the /config/config.php file can be controlled on the first day and it does NOT work:

$conf['settings']['first.day.of.week'] = '1';

Could you tell me how to change it?

![Captura](https://github.com/LibreBooking/app/assets/47590608/494e1f11-52cc-4ac3-b97a-1d6b18104b5f)

Thank you

**Comment by ieovigo** [comment]
Hello, 

It Works !

Thank you very much for the solution.

**Comment by treborin** [comment]
@ieovigo ,

Good!! No problem

Pls., close this issue
