### ISSUE TITLE
Version 2.8.6.2 not working

### ISSUE THREAD

**Issue by abaldoni** [LibreBooking/app#404]
Version 2.8.6.2 does not start due to the following error:

PHP message: PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/opt/librebooking/tpl/globalfooter.tpl"  on line 20 "function gtag(){dataLayer.push(arguments);}"  - Unexpected ".", expected one of: "}" <-- 

Current environment:
  PHP 8.1.27
  PHP-FPM 8.1.27
  NGINX 1.20.1

**Comment by effgarces** [comment]
Thank you for the report, I just pushed a new update and fixed the release (hopefully). You can simply download the "globalfooter.tpl" file from the "tpl" folder and replace on your install. Please test it

**Comment by abaldoni** [comment]
Thank you, it worked!
