### ISSUE TITLE
UTF8MB4 incompatibility causes ERROR 1366 in MariaDB

### ISSUE THREAD

**Issue by hakito** [LibreBooking/app#405]
One user tried to create a reservation with the title: ```Funny 🤡 title```

The clown face is 4 byte unicode character ```\xf0\x9f\xa4\xa1```

When trying to save the reservation it failed, but the user did not get a feedback for the reason.

In the log I saw the message:

> Error saving reservation: mysqli_sql_exception: Incorrect string value: '\xF0\x9F\xA4\xA1' for column librebooking.reservation_series.title at row 1 in

LibreBooking uses the charset `utf8` wich [normally corresponds to `utf8mb3`](https://mariadb.com/kb/en/unicode/) (also for mysql). 

I'd suggest to change all `utf8` fields and the mysqli connection to `utf8mb4`. Are there any counter-arguments?

**Comment by effgarces** [comment]
Not really, at least I'm not seeing downsides to this change.

**Comment by hakito** [comment]
@effgarces The PR is ready for review

**Comment by effgarces** [comment]
Thank you, I had a small opening this weekend and I'm going through the PR's
