### ISSUE TITLE
Huge jump in size of distribution

### ISSUE THREAD

**Issue by cgutteridge** [LibreBooking/app#418]
Something in the dependencies in the last bugfix seems to have put the distribution up to 200Mb when unzipped!

**Comment by PatH007** [comment]
For my version it seems the size is even superior to 240 Mb unzipped.

**Comment by effgarces** [comment]
Yes, it was quite a jump, it has to do with the dependencies, specifically the ones to connect to google/office365/facebook and allow for login using oauth authentication. If you are not using that you can probably just remove then (haven't tested it).

**Comment by cgutteridge** [comment]
We hope to get SAML to MS Azure working so I probably do need them.  But I guess I'll close this as "not really solvable".
