### ISSUE TITLE
Request: Docker container

### ISSUE THREAD

**Issue by lukebarone** [LibreBooking/app#60]
I'd love if there was a docker version that I can deploy.

**Comment by olivierbicler** [comment]
Docker file is quite simple, actually.
I attached the docker-compose.yml and Dockerfile we're using, just put in a subdirectory on root dir.
If you have php directives, put them in php.ini (not mandatory), else just delete the line in the docker-compose.yml.

Not quite sure each php ext is useful, and xdebug is only for debugging, of course.

[docker-compose.yml.txt](https://github.com/effgarces/BookedScheduler/files/6797238/docker-compose.yml.txt)
[Dockerfile.txt](https://github.com/effgarces/BookedScheduler/files/6797240/Dockerfile.txt)
